### ISSUE TITLE
Suggestions for additional features

### ISSUE THREAD

**Issue by slomanl1** [leinich/hassio-addons#1]
A few items to consider:
Trigger backup from frontend button
Trigger backup on a schedule
Trigger backup on a change to a file or group of files (poll for changes)
Trigger backup from an external curl request, or through the HASS API, or IFTTT

**Comment by leinich** [comment]
Thanks for yoru feedback
1) Trigger backup from frontend button
This should be already possible by invoking a script via HA
2) Trigger backup on a schedule
This is also already possible, e.g.:

```
- action:
  - data:
      addon: c80014cb_ftpbackup
    service: hassio.addon_start
  alias: Backup daily at 2am
  trigger:
  - at: 02:00
    platform: time
```

3) Trigger backup on

 a change to a file or group of files (poll for changes)
I don't like the idea to keep the addon running all the time.
But I will definitely look into a possibility to perform only backups if there were changes meanwhile in the configuration.
I'll close this request and open another one for this enhancement.
4) Trigger backup from an external curl request, or through the HASS API, or IFTTT
This is also possible by external starting the script from 1)
