### ISSUE TITLE
Automating FTP backup

### ISSUE THREAD

**Issue by langestefan** [leinich/hassio-addons#5]
Hi, thank you for the nice addon, it works great. I have one question: how do I automate this?

**Comment by leinich** [comment]
Should be possible via Script or automation.
```
- action:
  - data:
      addon: c80014cb_ftpbackup
    service: hassio.addon_start
  alias: Backup daily at 2am
  trigger:
  - at: 02:00
    platform: time
````
